#! /bin/sh
 
RTNETPATH=/usr/local/rtnet/sbin/

case "$1" in
start)
echo "starting rtnet from $RTNETPATH"
ifdown eth0
ifdown eth1
ifdown eth2
ifdown eth3
ifdown eth4
rmmod e1000e
sleep 1
insmod /usr/local/rtnet/modules/rtnet.ko
sleep 1
insmod /usr/local/rtnet/modules/rtipv4.ko
insmod /usr/local/rtnet/modules/rtcfg.ko
insmod /usr/local/rtnet/modules/rtpacket.ko

# insmod /usr/local/rtnet/modules/rt_e1000.ko InterruptThrottleRate=0,0,0,0 RxIntDelay=200,200,200,200 RxAbsIntDelay=750,750,750,750 XsumRX=1,1,1,1 TxIntDelay=0,0,0,0 TxAbsIntDelay=0,0,0,0 cards=1,1,1,1
insmod /usr/local/rtnet/modules/rt_e1000.ko cards=1,1,1,1

sleep 1
insmod /usr/local/rtnet/modules/rtcap.ko
echo "rtifconfig..."
$RTNETPATH/rtifconfig rteth0 up 192.168.1.100 netmask 255.255.255.0 hw ether 00:1b:21:8c:96:b9
$RTNETPATH/rtifconfig rteth1 up 192.168.2.100 netmask 255.255.255.0 hw ether 00:1b:21:8c:96:b8
$RTNETPATH/rtifconfig rteth2 up 192.168.3.100 netmask 255.255.255.0 hw ether 00:1b:21:8c:96:bb
$RTNETPATH/rtifconfig rteth3 up 192.168.4.100 netmask 255.255.255.0 hw ether 00:1b:21:8c:96:ba
$RTNETPATH/rtifconfig
echo "rtroute..."
# left leg
#$RTNETPATH/rtroute add 192.168.2.1 0:0:0:22:34:57 dev rteth1
#$RTNETPATH/rtroute add 192.168.2.2 0:0:0:22:34:57 dev rteth1
#$RTNETPATH/rtroute add 192.168.2.3 0:0:0:22:34:58 dev rteth1
#$RTNETPATH/rtroute add 192.168.2.4 0:0:0:22:34:59 dev rteth1
#$RTNETPATH/rtroute add 192.168.2.5 0:0:0:22:34:5A dev rteth1
#$RTNETPATH/rtroute add 192.168.2.6 0:0:0:22:34:5B dev rteth1
#$RTNETPATH/rtroute add 192.168.2.7 0:0:0:22:34:5C dev rteth1
#$RTNETPATH/rtroute add 192.168.2.8 0:0:0:22:34:5D dev rteth1
#$RTNETPATH/rtroute add 192.168.2.9 0:0:0:22:34:5E dev rteth1
# right arm
$RTNETPATH/rtroute add 192.168.3.1 0:0:0:32:34:56 dev rteth0
$RTNETPATH/rtroute add 192.168.3.2 0:0:0:32:34:57 dev rteth0
$RTNETPATH/rtroute add 192.168.3.3 0:0:0:32:34:58 dev rteth0
$RTNETPATH/rtroute add 192.168.3.4 0:0:0:32:34:59 dev rteth0
$RTNETPATH/rtroute add 192.168.3.5 0:0:0:32:34:5A dev rteth0
$RTNETPATH/rtroute add 192.168.3.6 0:0:0:32:34:5B dev rteth0
$RTNETPATH/rtroute add 192.168.3.7 0:0:0:32:34:5C dev rteth0
$RTNETPATH/rtroute add 192.168.3.8 0:0:0:32:34:5D dev rteth0
# left arm
$RTNETPATH/rtroute add 192.168.4.1 0:0:0:42:34:56 dev rteth0
$RTNETPATH/rtroute add 192.168.4.2 0:0:0:42:34:57 dev rteth0
$RTNETPATH/rtroute add 192.168.4.3 0:0:0:42:34:58 dev rteth0
$RTNETPATH/rtroute add 192.168.4.4 0:0:0:42:34:59 dev rteth0
$RTNETPATH/rtroute add 192.168.4.5 0:0:0:42:34:5A dev rteth0
$RTNETPATH/rtroute add 192.168.4.6 0:0:0:42:34:5B dev rteth0
$RTNETPATH/rtroute add 192.168.4.7 0:0:0:42:34:5C dev rteth0
$RTNETPATH/rtroute add 192.168.4.8 0:0:0:42:34:5D dev rteth0
# right leg
#$RTNETPATH/rtroute add 192.168.5.1 0:0:0:52:34:56 dev rteth0
#$RTNETPATH/rtroute add 192.168.5.2 0:0:0:52:34:57 dev rteth0
#$RTNETPATH/rtroute add 192.168.5.3 0:0:0:52:34:58 dev rteth0
#$RTNETPATH/rtroute add 192.168.5.4 0:0:0:52:34:59 dev rteth0
#$RTNETPATH/rtroute add 192.168.5.5 0:0:0:52:34:5A dev rteth0
#$RTNETPATH/rtroute add 192.168.5.6 0:0:0:52:34:5B dev rteth0
#$RTNETPATH/rtroute add 192.168.5.7 0:0:0:52:34:5C dev rteth0
#$RTNETPATH/rtroute add 192.168.5.8 0:0:0:52:34:5D dev rteth0
# head
$RTNETPATH/rtroute add 192.168.1.1 0:0:0:12:34:56 dev rteth0
$RTNETPATH/rtroute add 192.168.1.2 0:0:0:12:34:57 dev rteth0
$RTNETPATH/rtroute add 192.168.1.3 0:0:0:12:34:58 dev rteth0
$RTNETPATH/rtroute add 192.168.1.4 0:0:0:12:34:59 dev rteth0
$RTNETPATH/rtroute add 192.168.1.5 0:0:0:12:34:5A dev rteth0
$RTNETPATH/rtroute add 192.168.1.6 0:0:0:12:34:5B dev rteth0
$RTNETPATH/rtroute add 192.168.1.7 0:0:0:12:34:5C dev rteth0
$RTNETPATH/rtroute add 192.168.1.8 0:0:0:12:34:5D dev rteth0
#$RTNETPATH/rtroute
ifconfig rteth0 up
ifconfig rteth1 up
ifconfig rteth2 up
ifconfig rteth3 up
ifconfig
echo "Loading non-rt ethernet..."
modprobe e1000e
sleep 1
ifconfig eth4 up
;;
restart)
$0 stop
$0 start
;;
stop)
echo "stopping rtnet from $RTNETPATH"
echo "rtifconfig..."
$RTNETPATH/rtifconfig rtlo down
$RTNETPATH/rtifconfig rteth0 down
$RTNETPATH/rtifconfig rteth1 down
$RTNETPATH/rtifconfig rteth2 down
$RTNETPATH/rtifconfig rteth3 down
rmmod rtcap.ko
rmmod rt_e1000.ko
sleep 1
rmmod rtpacket.ko
rmmod rtcfg.ko
rmmod rt_loopback.ko
rmmod rtipv4.ko
rmmod rtnet.ko
;;
*)
echo $"usage: $0 {start|stop|restart}"
exit 3
;;
esac
: